# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Litestar service template 🌠
reponame: template-service-litestar
repourl: https://github.com/radio-aktywne/template-service-litestar
templatename: litestar
type: service
